import os

FLASK_APP_SECRET_KEY = os.environ.get("FLASK_APP_SECRET_KEY")

DATABASE_HOST = os.environ.get("DATABASE_HOST")
DATABASE_PORT = os.environ.get("DATABASE_PORT")
DATABASE_USER = os.environ.get("DATABASE_USER")
DATABASE_PASSWORD = os.environ.get("DATABASE_PASSWORD")
DATABASE_SCHEMA_NAME = os.environ.get("DATABASE_SCHEMA_NAME")

TEST_CONTAINER_IMAGE = "mysql:9.0.1"
FLASK_DEBUG_MODE = True if not os.environ.get("IS_PRODUCTION") else False
FLASK_HOST = "0.0.0.0"
FLASK_PORT = 5000
