services:
  app:
    depends_on:
      - db
    links:
      - db
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env

  db:
    image: mysql:9.0.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
