DROP TABLE attendance_record;
DROP TABLE attendance_session;
DROP TABLE enrollment;
DROP TABLE page_file_bridge;
DROP TABLE page;
DROP TABLE file;
DROP TABLE course;
DROP TABLE course_term;
DROP TABLE user;