DROP TABLE attendance_record;
DROP TABLE attendance_session;
DROP TABLE enrollment;
DROP TABLE page_file_bridge;
DROP TABLE page;
DROP TABLE class;
DROP TABLE file;
DROP TABLE class_term;
DROP TABLE user;